In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Dataset_Hackathon.csv')

In [3]:
data

Country                                          Commodity       Flow  \
0      Albania  Poultry cuts & offal, except livers, fresh or ...     Export   
1      Albania  Poultry cuts & offal, except livers, fresh or ...     Export   
2      Albania  Swine meat, salted/dried/smoked not ham/should...     Export   
3      Albania                     Fowls, domestic, whole, frozen     Export   
4      Albania  Meat and edible offal nes fresh, chilled or fr...     Export   
...        ...                                                ...        ...   
81440   Malawi               Oil seeds and oleaginous fruits, nes     Export   
81441   Malawi               Seed, beet, except sugar, for sowing     Export   
81442   Malawi                                         Soya beans     Export   
81443   Malawi         Ground-nuts in shell not roasted or cooked     Export   
81444   Malawi         Ground-nuts in shell not roasted or cooked  Re-Export   

       Quantity                                           Category  \
0            34                      02_meat_and_edible_meat_offal   
1            23                      02_meat_and_edible_meat_offal   
2            11                      02_meat_and_edible_meat_offal   
3            50                      02_meat_and_edible_meat_offal   
4            71                      02_meat_and_edible_meat_offal   
...         ...                                                ...   
81440        85  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...   
81441         3  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...   
81442         1  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...   
81443         6  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...   
81444         6  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...   

       Volume (m^3)  Distance from India (m)  Frieght Cost (USD)  
0                12              5940.830501         4840.697837  
1                12              5940.830501         3069.710823  
2                12              5940.830501         1475.822511  
3                12              5940.830501         7083.948054  
4                12              5940.830501         9976.560176  
...             ...                      ...                 ...  
81440             4              6170.000164         2767.338021  
81441             4              6170.000164          162.784589  
81442             4              6170.000164          162.784589  
81443             4              6170.000164          284.873032  
81444             4              6170.000164          256.385728  

[81445 rows x 8 columns]

In [4]:
new_data = data.drop(['Country','Flow','Frieght Cost (USD)','Quantity','Volume (m^3)','Distance from India (m)','Frieght Cost (USD)'], axis = 1)

In [5]:
new_data

Commodity  \
0      Poultry cuts & offal, except livers, fresh or ...   
1      Poultry cuts & offal, except livers, fresh or ...   
2      Swine meat, salted/dried/smoked not ham/should...   
3                         Fowls, domestic, whole, frozen   
4      Meat and edible offal nes fresh, chilled or fr...   
...                                                  ...   
81440               Oil seeds and oleaginous fruits, nes   
81441               Seed, beet, except sugar, for sowing   
81442                                         Soya beans   
81443         Ground-nuts in shell not roasted or cooked   
81444         Ground-nuts in shell not roasted or cooked   

                                                Category  
0                          02_meat_and_edible_meat_offal  
1                          02_meat_and_edible_meat_offal  
2                          02_meat_and_edible_meat_offal  
3                          02_meat_and_edible_meat_offal  
4                          02_meat_and_edible_meat_offal  
...                                                  ...  
81440  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81441  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81442  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81443  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81444  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  

[81445 rows x 2 columns]

In [6]:
new_data['Commodity'] = new_data['Commodity'].apply(lambda x:x.split())

In [7]:
df1=new_data

In [8]:
df1

Commodity  \
0      [Poultry, cuts, &, offal,, except, livers,, fr...   
1      [Poultry, cuts, &, offal,, except, livers,, fr...   
2      [Swine, meat,, salted/dried/smoked, not, ham/s...   
3                    [Fowls,, domestic,, whole,, frozen]   
4      [Meat, and, edible, offal, nes, fresh,, chille...   
...                                                  ...   
81440        [Oil, seeds, and, oleaginous, fruits,, nes]   
81441        [Seed,, beet,, except, sugar,, for, sowing]   
81442                                      [Soya, beans]   
81443  [Ground-nuts, in, shell, not, roasted, or, coo...   
81444  [Ground-nuts, in, shell, not, roasted, or, coo...   

                                                Category  
0                          02_meat_and_edible_meat_offal  
1                          02_meat_and_edible_meat_offal  
2                          02_meat_and_edible_meat_offal  
3                          02_meat_and_edible_meat_offal  
4                          02_meat_and_edible_meat_offal  
...                                                  ...  
81440  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81441  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81442  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81443  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  
81444  12_oil_seed_oleagic_fruits_grain_seed_fruit_et...  

[81445 rows x 2 columns]

In [9]:
df1['Category'].replace("[^0-9]"," ",regex=True, inplace=True)
#df['Flow'].replace(['Export', 'Re-Export'], [0, 1], inplace = True)
df1['Category'] = pd.Series(df1['Category'], dtype="int64")

In [10]:
df1

Commodity  Category
0      [Poultry, cuts, &, offal,, except, livers,, fr...         2
1      [Poultry, cuts, &, offal,, except, livers,, fr...         2
2      [Swine, meat,, salted/dried/smoked, not, ham/s...         2
3                    [Fowls,, domestic,, whole,, frozen]         2
4      [Meat, and, edible, offal, nes, fresh,, chille...         2
...                                                  ...       ...
81440        [Oil, seeds, and, oleaginous, fruits,, nes]        12
81441        [Seed,, beet,, except, sugar,, for, sowing]        12
81442                                      [Soya, beans]        12
81443  [Ground-nuts, in, shell, not, roasted, or, coo...        12
81444  [Ground-nuts, in, shell, not, roasted, or, coo...        12

[81445 rows x 2 columns]

In [11]:
df1.index.name = 'id'

In [12]:
df1.head()

Commodity  Category
id                                                             
0   [Poultry, cuts, &, offal,, except, livers,, fr...         2
1   [Poultry, cuts, &, offal,, except, livers,, fr...         2
2   [Swine, meat,, salted/dried/smoked, not, ham/s...         2
3                 [Fowls,, domestic,, whole,, frozen]         2
4   [Meat, and, edible, offal, nes, fresh,, chille...         2

In [13]:
df1

Commodity  Category
id                                                                
0      [Poultry, cuts, &, offal,, except, livers,, fr...         2
1      [Poultry, cuts, &, offal,, except, livers,, fr...         2
2      [Swine, meat,, salted/dried/smoked, not, ham/s...         2
3                    [Fowls,, domestic,, whole,, frozen]         2
4      [Meat, and, edible, offal, nes, fresh,, chille...         2
...                                                  ...       ...
81440        [Oil, seeds, and, oleaginous, fruits,, nes]        12
81441        [Seed,, beet,, except, sugar,, for, sowing]        12
81442                                      [Soya, beans]        12
81443  [Ground-nuts, in, shell, not, roasted, or, coo...        12
81444  [Ground-nuts, in, shell, not, roasted, or, coo...        12

[81445 rows x 2 columns]

In [14]:
df1['Commodity'].apply(lambda x:" ".join(x))

id
0        Poultry cuts & offal, except livers, fresh or ...
1        Poultry cuts & offal, except livers, fresh or ...
2        Swine meat, salted/dried/smoked not ham/should...
3                           Fowls, domestic, whole, frozen
4        Meat and edible offal nes fresh, chilled or fr...
                               ...                        
81440                 Oil seeds and oleaginous fruits, nes
81441                 Seed, beet, except sugar, for sowing
81442                                           Soya beans
81443           Ground-nuts in shell not roasted or cooked
81444           Ground-nuts in shell not roasted or cooked
Name: Commodity, Length: 81445, dtype: object

In [15]:
df1['Commodity']=new_data['Commodity'].apply(lambda x:" ".join(x))


In [16]:
df1

Commodity  Category
id                                                                
0      Poultry cuts & offal, except livers, fresh or ...         2
1      Poultry cuts & offal, except livers, fresh or ...         2
2      Swine meat, salted/dried/smoked not ham/should...         2
3                         Fowls, domestic, whole, frozen         2
4      Meat and edible offal nes fresh, chilled or fr...         2
...                                                  ...       ...
81440               Oil seeds and oleaginous fruits, nes        12
81441               Seed, beet, except sugar, for sowing        12
81442                                         Soya beans        12
81443         Ground-nuts in shell not roasted or cooked        12
81444         Ground-nuts in shell not roasted or cooked        12

[81445 rows x 2 columns]

In [17]:
import sklearn

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
#object 
cv = CountVectorizer(max_features=5000,stop_words='english')

In [19]:
vectors = cv.fit_transform(df1['Commodity']).toarray()

In [20]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
vectors[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
import nltk

In [23]:
from nltk.stem.porter import PorterStemmer

In [24]:
def stem(text):
    y=[]
    ps = PorterStemmer()
  
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [25]:
stem(df1['Commodity'][0])

'poultri cut & offal, except livers, fresh or chill'

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
#object 
cv = CountVectorizer(max_features=5000,stop_words='english')

In [27]:
vectors = cv.fit_transform(new_data['Commodity']).toarray()

In [28]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
vectors[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [30]:
cv.get_feature_names_out()

array(['acid', 'adzuki', 'albacore', 'alfalfa', 'algae', 'alliaceous',
       'almonds', 'ambergris', 'anchovies', 'animal', 'animals', 'anise',
       'apples', 'apricot', 'apricots', 'aquatic', 'arrowroot',
       'artichokes', 'asparagus', 'ass', 'atlantic', 'aubergines',
       'avocados', 'azaleas', 'badger', 'badian', 'bananas', 'barley',
       'bass', 'bay', 'bean', 'beans', 'beet', 'beetroot', 'bell',
       'bellied', 'bellies', 'belly', 'berries', 'bilberries', 'bird',
       'birds', 'black', 'blackberry', 'bladders', 'blue', 'boars',
       'boil', 'boiled', 'bone', 'boneless', 'bones', 'bonito',
       'bouquets', 'bovine', 'branches', 'brassicas', 'brazil', 'brine',
       'brisling', 'bristles', 'broad', 'broccoli', 'broken', 'brown',
       'brush', 'brussels', 'buckwheat', 'buds', 'bulbs', 'bushes',
       'butter', 'buttermilk', 'cabbage', 'canary', 'cane', 'capers',
       'capsicum', 'caraway', 'carcass', 'carcasses', 'cardamoms', 'carp',
       'carrots', 'cashew'

In [31]:
from sklearn.metrics.pairwise import cosine_similarity 

In [ ]:
similarity = cosine_similarity(vectors)